[build]
  command = "npm run build"
  publish = "dist" # or "build" if you’re using CRA

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
  